version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 20
    versioning-strategy: increase
    target-branch: "main"
    labels:
      - "dependencies"
    reviewers:
      - reiroop
