name: common

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  dependencies:
    name: Prepare packages and Generate apis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
      - run: npm ci
      - uses: actions/upload-artifact@v2
        with:
          name: apis
          path: ./src/lib/apis/generated
  type-check: 
    name: Type Check
    runs-on: ubuntu-latest
    needs: [dependencies]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
      - run: npm ci
      - uses: actions/download-artifact@v2
        with:
          name: apis
          path: ./src/lib/apis/generated
      - run: npm run type-check
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [dependencies]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
      - run: npm ci
      - uses: actions/download-artifact@v2
        with:
          name: apis
          path: ./src/lib/apis/generated
      - run: npm run lint
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [dependencies]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
      - run: npm ci
      - uses: actions/download-artifact@v2
        with:
          name: apis
          path: ./src/lib/apis/generated
      - run: npm run build
