name: main

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  packages:
    name: Install node_modules
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [packages]
    env:
      CI: true
      NODE_ENV: production
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node_modules-
      - run: npm run lint
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [packages]
    env:
      CI: true
      NODE_ENV: production
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node_modules-
      - run: npm run build
