name: main

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  packages:
    name: Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm ci
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/upload-artifact@v2
        with:
          name: apis
          path: ./src/lib/apis/generated
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [packages]
    env:
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node_modules-
      - uses: actions/download-artifact@v2
        with:
          name: apis
          path: ./src/lib/apis/generated
      - run: npm run lint
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [packages]
    env:
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node_modules-
      - uses: actions/download-artifact@v2
        with:
          name: apis
          path: ./src/lib/apis/generated
      - run: npm run build
